spring.application.name=smart_parking

mqtt.broker.url=${MQTT_BROKER_URL}
mqtt.client.id=${MQTT_CLIENT_ID}
mqtt.default.topic=${MQTT_DEFAULT_TOPIC}
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}

server.port=${PORT:8080}
